### ISSUE TITLE
Create Kanaban board, and Assign tasks.

### ISSUE THREAD

**Issue by ibr5500** [ibr5500/flight_reservation-backend#1]
GitHub project: https://github.com/users/ibr5500/projects/6

Note: There are 4 members in this team.

member 1: @GOlivierNation
member 2: @NatiG25
member 3: @KanoCode
member 4: @ibr5500

Screenshot:

<img width="956" alt="Screenshot 2022-09-22 174509" src="https://user-images.githubusercontent.com/48220903/191778744-2b5250cd-4915-4808-beda-93118d2815fb.png">

**Comment by mcrd25** [comment]
Hi Team, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your board.

## Invalid Code Review Request

You have submitted a project, that does not contain a screenshot of the current state of the Kanban Board at the time of review request which is seen as a requirement [here](https://github.com/microverseinc/curriculum-final-capstone/blob/main/projects/setup_kanban_board.md)

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**_Please, do not open a new Issue for re-reviews. You should use the same Issue submitted for the first review, either valid or invalid unless it is requested otherwise._**

**Comment by mcrd25** [comment]
Hi Team, 

In my opinion, you are ready to move on to the next step! ⏭️  


Good luck! 🎉 


Feel free to leave any questions or comments in the Issue thread if something is not 100% clear.

**Comment by ibr5500** [comment]
Thank you @mcrd25 for the review
